export const Permissions = [
  'STAFFMEM',
  'ROLE',
  'WORKFLOW',
  'TICKET',
  'BRAND',
  'CATEGORY',
  'PRODUCT',
  'DASHBOARD',
  'STOCKADJUST',
  'WAREHOUSE',
  'SUPPLIER',
  'CUSTOMER',
  'EXPENSECATEGORY',
  'EXPENSE',
  'POS',
  'CASHANDBANK',
  'SETTINGS',
  'SALES',
  'STOCKTRANSFER',
  'PURCHASE',
  'REPORT',
] as const;

export const Roles = ['ADMIN'] as const;
